language: node_js

cache:
  directories:
    - "node_modules"

before_script:
  - ./scripts/install.sh

deploy:
  - provider: script
    script: "./scripts/deploy.sh"
    skip_cleanup: true
    on:
      branch: master

branches:
  only:
  - master
