#!/bin/bash

set -e
set -u

# Generates a file input file with random data

FILE="spec/input-data/big-input.json"
ENTRIES=90000

echo "# File automatically generated by $0" > $FILE
echo "[" > $FILE

for i in `seq 1 $ENTRIES`; do
  echo "{ \"id\": \"a\", \"timestamp\": 1509493${i},\"temperature\": $(($RANDOM % 10)).$(($RANDOM % 100))}" >> $FILE
  if [[ "$i" != "$ENTRIES" ]]; then
    echo "," >> $FILE
  fi
  if (( $i % 100 == 0 )); then
    echo -n "."
  fi
done

echo "]" >> $FILE
